// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Chores   string
	Families string
	Redeemed string
	Rewards  string
	Users    string
}{
	Chores:   "chores",
	Families: "families",
	Redeemed: "redeemed",
	Rewards:  "rewards",
	Users:    "users",
}
