// Code generated by mockery v2.43.2. DO NOT EDIT.

package family

import (
	context "context"

	model "github.com/sonnyzxc/drp/be_drp32/api/internal/controller/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// CreateFamily provides a mock function with given fields: ctx, familyName
func (_m *MockRepository) CreateFamily(ctx context.Context, familyName string) (model.Family, error) {
	ret := _m.Called(ctx, familyName)

	if len(ret) == 0 {
		panic("no return value specified for CreateFamily")
	}

	var r0 model.Family
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Family, error)); ok {
		return rf(ctx, familyName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Family); ok {
		r0 = rf(ctx, familyName)
	} else {
		r0 = ret.Get(0).(model.Family)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, familyName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFamilyByID provides a mock function with given fields: ctx, familyID
func (_m *MockRepository) GetFamilyByID(ctx context.Context, familyID int64) (model.Family, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetFamilyByID")
	}

	var r0 model.Family
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Family, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Family); ok {
		r0 = rf(ctx, familyID)
	} else {
		r0 = ret.Get(0).(model.Family)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
