// Code generated by mockery v2.43.2. DO NOT EDIT.

package chore

import (
	context "context"

	model "github.com/sonnyzxc/drp/be_drp32/api/internal/controller/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

// CreateChore provides a mock function with given fields: ctx, desc, points, assignedTo, dueDate
func (_m *MockController) CreateChore(ctx context.Context, desc string, points int, assignedTo int64, dueDate time.Time) error {
	ret := _m.Called(ctx, desc, points, assignedTo, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for CreateChore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int64, time.Time) error); ok {
		r0 = rf(ctx, desc, points, assignedTo, dueDate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFamilyChores provides a mock function with given fields: ctx, familyID
func (_m *MockController) GetFamilyChores(ctx context.Context, familyID int64) (model.Chores, error) {
	ret := _m.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetFamilyChores")
	}

	var r0 model.Chores
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (model.Chores, error)); ok {
		return rf(ctx, familyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) model.Chores); ok {
		r0 = rf(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Chores)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
