// Code generated by mockery v2.43.2. DO NOT EDIT.

package chore

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

// CreateChore provides a mock function with given fields: ctx, desc, points, assignedTo, dueDate
func (_m *MockController) CreateChore(ctx context.Context, desc string, points int, assignedTo int64, dueDate time.Time) error {
	ret := _m.Called(ctx, desc, points, assignedTo, dueDate)

	if len(ret) == 0 {
		panic("no return value specified for CreateChore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int64, time.Time) error); ok {
		r0 = rf(ctx, desc, points, assignedTo, dueDate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
