name: DRP32 CI/CD (React Native)

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        run: cd HouseholdHero && npm ci

      - name: Run Tests
        run: cd HouseholdHero && npm test -- --watchAll=false

      - name: Prebuild Expo
        # if: contains('ci', github.ref)
        run: cd HouseholdHero && npx expo prebuild

      - name: Build Android
        # if: contains('ci', github.ref)
        run: cd HouseholdHero/android && ./gradlew assembleRelease

      - name: Check files
        # if: contains('ci', github.ref)
        run: ls HouseholdHero/android/app/build/outputs/apk/release

      - name: Upload APK
        # if: contains('ci', github.ref)
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: HouseholdHero/android/app/build/outputs/apk/release/app-release.apk
